### ISSUE TITLE
Question: What is the correct way to pass in a List-type parameter?

### ISSUE THREAD

**Issue by io7m** [takari/takari-plugin-testing-project#12]
I have a mojo with the following:

```
@Parameter private List<String> packages;
```

I notice that I can pass in individual string parameters using the `TestRuntime`:

```
this.maven.executeMojo(basedir, "some-goal", TestMavenRuntime.newParameter("key", "value"));
```

... but there doesn't appear to be an equivalent for passing in parameters of any other type. It seems that internally, the method creates values of type `Xpp3Dom`, but there's apparently no documentation on how to go about doing this for other types.

**Comment by io7m** [comment]
Some digging gave me the answer:

```
final Xpp3Dom p = new Xpp3Dom("param");
p.setValue("a-package-name");
final Xpp3Dom ps = new Xpp3Dom("packages");
ps.addChild(p);
this.maven.executeMojo(basedir, "some-goal", ps);
```

**Comment by ifedorenko** [comment]
Maybe we should introduce `Xpp3Dom newListParameter(String name, String... elements)` helper.
