### ISSUE TITLE
Access to repositories from tests?

### ISSUE THREAD

**Issue by guw** [takari/takari-plugin-testing-project#15]
I was trying to write a unit tests for testing a mojo. The mojo looks up an artifact from whatever repositories are configured. Running the unit test from within Eclipse, I get the following error.

```
org.apache.maven.plugin.MojoExecutionException: Unable to retrieve available versions for artifact org.jsoup:jsoup:RELEASE. No versioning information available in repository metadata.
...
```

In the console I can see the following error:

```
[WARNING] repository metadata for: 'artifact org.jsoup:jsoup' could not be retrieved from repository: central due to an error: Unsupported Protocol: 'https': Cannot find wagon which supports the requested protocol: https
```

Is it possible that this is disabled on purpose? Is there a suggestion how to "inject" a repository? I'm totally happy not having to rely on central for a unit test.

**Comment by ifedorenko** [comment]
`'https': Cannot find wagon` most likely means http wagon is not present on the test classpath. the easiest is to add file and http wagons to your plugin dependencies with scope=test, let me know if you need help. longer term is probably better to avoid remote repositories access during the test. this is what we plan to do internally where I work ;-)

PS: sorry for the late reply, github still loses emails it seems and I missed the question.

**Comment by guw** [comment]
Thanks! That's no longer an issue.
