### ISSUE TITLE
Support populating MavenProjects resolvedArtifacts

### ISSUE THREAD

**Issue by jvanzyl** [takari/takari-plugin-testing-project#2]
Currently if you have a Mojo that uses ${project.artifacts}, it will not be populated because the logic that does this in Maven is not executed in the harness. It's debatable whether we want this for unit tests but we would need an equivalent LifecycleDependencyResolver.resolveProjectDependencies which populates the resolvedArtifacts field which is in turn used by Maven.getArtifacts() with a scope to make ${project.artifacts} available in a Mojo.

I am working on a WAR mojo and a shade-like mojo which does need to test which artifacts have been resolved. We might be able to use the LifecycleDependencyResolver component directly to get parity with Maven.

**Comment by ifedorenko** [comment]
In my tests I simply create dummy Artifact instances and call MavenProject.setArtifacts. This approach requires ~1 line of test code for each dependency, so it is very light. It also gives very fine control over dependencies used by the tests and makes testing incremental behaviour quite easy.

**Comment by ifedorenko** [comment]
I consider this is done. It is possible to populate test project dependencies with arbitrary files using `TestMavenRuntime.newDependency(artifact).addTo(project)` API. It is also possible to pass main project dependencies to the test using `property=${groupId:artifactId[:classifier]}` named properties in `src/test/test.properties` file. This gives test developers complete control over both coordinates and contents of the artifacts "resolved" by the test projects.

**Comment by spwilliams-hubspot** [comment]
I've got the same problem here, writing a plugin that needs to inspect the dependency tree of a project (and retrieve the contents of a text file in the classpath resources of direct dependencies) -- which I can't do without some way to populate the actual artifact jars.

I'd love to be able to test this as an integration test, but I don't have a way to get individual components or mojos to test them -- I'd have to spit everything out to the log
