### ISSUE TITLE
User settings do not work as expected.

### ISSUE THREAD

**Issue by Buuhuu** [takari/takari-plugin-testing-project#3]
The users settings file is named in the test.properties different then it is expected in the testing plugin

https://github.com/takari/takari-plugin-testing-project/blob/master/takari-plugin-testing/src/main/java/io/takari/maven/testing/TestProperties.java

    public static final String PROP_USER_SETTING = "userSettings";

And in https://github.com/takari/takari-lifecycle/blob/master/takari-lifecycle-plugin/src/main/java/io/takari/maven/plugins/testproperties/TestPropertiesMojo.java

    if (userSettingsFile != null) {
        putIfAbsent(properties, "userSettingsFile", userSettingsFile.getAbsolutePath());
    }

Additionally the user settings are not populated to the MavenSession and RepositorySystemSession as it is done by MavenCli.

**Comment by ifedorenko** [comment]
Do you happen to have a sample project that shows the problem with MavenSession and RepositorySystemSession not being populated properly? `MavenRuntime#newMavenSession()` is supposed to populate both sessions from user settings.xml (after fixing property name, of course)
