### ISSUE TITLE
There is an extra level of directory nesting when a project is copied with TestResources#getBasedir(String)

### ISSUE THREAD

**Issue by Suseika** [takari/takari-plugin-testing-project#7]
Here is an excerpt from my test `GitVersionInsertMojoTest.java` class:

```java
    @Rule
    public final TestResources resources = new TestResources(
        "target/extracted-test-resources/",
        "target/test-projects/"
    );

    @Rule
    public final TestMavenRuntime maven = new TestMavenRuntime();

    @Test
    public void replacesToken() throws Exception {
        File basedir = this.resources.getBasedir("fake-maven-git");
        this.maven.executeMojo(
            basedir,
            "insert-version"
        );
        // ...
```

`this.resources.getBasedir("fake-maven-git");` copies directory

     target/extracted-test-resources/fake-maven-git

to 

    target/test-projects/GitVersionInsertMojoTest_replacesToken_fake-maven-git/fake-maven-git

, lets call that "long actual path".

But I expected the directory to be copied to 

        target/test-projects/GitVersionInsertMojoTest_replacesToken_fake-maven-git

instead, it's the same path without the last directory. Lets call that "short expected path".

The problem is that during `this.maven.executeMojo()` call, `${project.basedir}` is the "short expected path", but  all the project files are located at the "long actual path".

Am I missing something, or is this a bug?

**Comment by ifedorenko** [comment]
I tried to reproduce this problem locally but could not. Do you think you can fork and "break" https://github.com/ifedorenko/com.ifedorenko.sample-maven-plugin to illustrate the problem?

**Comment by Suseika** [comment]
Sorry for stealing your time, the issue was actually on my side. I had that extra nesting level in projects directory, my project was at `target/extracted-test-resources/fake-maven-git/fake-maven-git`.

**Comment by ifedorenko** [comment]
no worries. 

btw, any reason you don't use packaging=takari-maven-plugin? it's good. works inside m2e quite well too. :-)

**Comment by Suseika** [comment]
I'm planning to try that out as soon as I get the plugin working. Thanks for the great piece of software, works like a charm when I don't get confused with my own code : )
